language: cpp
compiler: gcc

env:
  global:
    - PATH=$PATH:$TRAVIS_BUILD_DIR/plugin-runner-1.1.2-linux

install:
  - sudo apt-add-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-4.4 gcc-4.4-multilib g++-4.4 g++-4.4-multilib cmake

  - wget https://github.com/Zeex/pawn/releases/download/20150412/pawnc-3.10.20150412-linux.tar.gz
  - sudo tar xvf pawnc-3.10.20150412-linux.tar.gz --strip-components=1 -C /usr/local
  - sudo ldconfig

  - wget https://github.com/Zeex/plugin-runner/releases/download/v1.1.2/plugin-runner-1.1.2-linux.tar.gz
  - tar xvf plugin-runner-1.1.2-linux.tar.gz

before_script:
  - cmake . -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_C_COMPILER=gcc-4.4
            -DCMAKE_CXX_COMPILER=g++-4.4

script:
  - make
  - make test
  - make package

after_failure:
  - cat Testing/Temporary/LastTest.log

deploy:
  provider: releases
  api_key:
    secure: H3zByVtEfSHCQtNZsbP/5l6uBkpbZ+T5eh3eKRjNYIEUS6OXl3Z9Rwl/ruYR7cCD863yHWf4iuXOYX4+VejzPxBjTGNcCtKmY6py7LyiTRFRn60hYKpBdJEA8Tj0z7EUG7g6gA/DkBkjbjqkY1nUW47e7IGSwhwSlvPxDneZ8Uk=
  file_glob: true
  file:
    - 'jit-*-linux.tar.gz'
  draft: true
  skip_cleanup: true
  on:
    repo: Zeex/samp-plugin-jit
    tags: true
